apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-prod
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-prod
  template:
    metadata:
      labels:
        app: guestbook-ui-prod
        eti: dffdkkffff

    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.1
          name: guestbook-ui-prod-test
          ports:
            - containerPort: 80
